### ISSUE TITLE
User name completion has duplicate items

### ISSUE THREAD

**Issue by amjith** [dbcli/mycli#316]
Related to https://github.com/dbcli/mycli/issues/305 and https://github.com/dbcli/mycli/issues/306

```
mysql root@localhost:_test_db> user
                                     ''@'amjith-mbp'     ''@'localhost'      'root'@'::1'        'root'@'amjith-mbp'
                                     ''@'amjith-mbp'     'root'@'127.0.0.1'  'root'@'::1'        'root'@'localhost'
                                     ''@'localhost'      'root'@'127.0.0.1'  'root'@'amjith-mbp' 'root'@'localhost'
```

**Comment by ushuz** [comment]
Still have this issue with 1.8.1

**Comment by johnksterling** [comment]
I was not able to reproduce this anymore given the other two issues are resolved.  Can you provide more info on what you are seeing?

**Comment by ushuz** [comment]
@johnksterling Try switch database by `USE test_db`, then completion for `USER` will contain duplicates. Each `USE` results in a new batch of duplicates.

**Comment by johnksterling** [comment]
Nice - I see it.  I think I can fix that, I'll submit a fix.

**Comment by amjith** [comment]
Yeah this is still an issue. The fix is to reset the `self.users` datastructure when we reset completions. 

Code: https://github.com/dbcli/mycli/blob/master/mycli/sqlcompleter.py#L193

**Comment by amjith** [comment]
Thanks for taking that on @johnksterling

**Comment by johnksterling** [comment]
#345 is submitted
